[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["ibrahim dursun <ibrahim.dursun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1"
path = "src/day1.rs"

[dependencies]
